// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGjHvDj7WGtYv1SKi01TXfEnyi4-kX4F4',
    appId: '1:783467945111:web:664b95328648dbef6cddd2',
    messagingSenderId: '783467945111',
    projectId: 'todo-ac1b6',
    authDomain: 'todo-ac1b6.firebaseapp.com',
    storageBucket: 'todo-ac1b6.appspot.com',
    measurementId: 'G-TM3X3R262Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6CBMrJGTKlbHeSOiT6e6niyjlh40zTGI',
    appId: '1:783467945111:android:000188af4408174c6cddd2',
    messagingSenderId: '783467945111',
    projectId: 'todo-ac1b6',
    storageBucket: 'todo-ac1b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHq01N66sZE_F1BNaFWea7yZZKaR_Yvk',
    appId: '1:783467945111:ios:77fda3021d2fde3b6cddd2',
    messagingSenderId: '783467945111',
    projectId: 'todo-ac1b6',
    storageBucket: 'todo-ac1b6.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhHq01N66sZE_F1BNaFWea7yZZKaR_Yvk',
    appId: '1:783467945111:ios:77fda3021d2fde3b6cddd2',
    messagingSenderId: '783467945111',
    projectId: 'todo-ac1b6',
    storageBucket: 'todo-ac1b6.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGjHvDj7WGtYv1SKi01TXfEnyi4-kX4F4',
    appId: '1:783467945111:web:5e6aec4961542c7f6cddd2',
    messagingSenderId: '783467945111',
    projectId: 'todo-ac1b6',
    authDomain: 'todo-ac1b6.firebaseapp.com',
    storageBucket: 'todo-ac1b6.appspot.com',
    measurementId: 'G-61SVFFX1XZ',
  );
}
